spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql'
    username: sa
    password:
  h2.console.enabled: true