spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./src/test/h2db/testdb;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql'
    username: sa
    password:
    initialization-mode: always
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
